DEFAULT_SEARCH_TIMEOUT = 0x1E

# Device types
DEVICE_TYPE_BIKE_POWER = 0x0b
DEVICE_TYPE_CONTROLLABLE_DEVICE = 0x10
DEVICE_TYPE_FITNESS_EQUIPMENT = 0x11
DEVICE_TYPE_BLOOD_PRESSURE = 0x12
DEVICE_TYPE_GEOCACHE = 0x13
DEVICE_TYPE_ENVIRONMENT = 0x19
DEVICE_TYPE_WEIGHT_SCALE = 0x77
DEVICE_TYPE_HEART_RATE = 0x78
DEVICE_TYPE_BIKE_SPEED_CADENCE = 0x79
DEVICE_TYPE_BIKE_CADENCE = 0x7a
DEVICE_TYPE_BIKE_SPEED = 0x7b
DEVICE_TYPE_STRIDE_SDM = 0x7c
DEVICE_TYPE_UNKNOWN = -0x01

# Channel configuration
BIDIRECTIONAL_SLAVE_CHANNEL = 0x00
BIDIRECTIONAL_MASTER_CHANNEL = 0x10
SHARED_BIDIRECTIONAL_SLAVE_CHANNEL = 0x20
SHARED_BIDIRECTIONAL_MASTER_CHANNEL = 0x30
SLAVE_RECEIVE_ONLY_CHANNEL = 0x40
MASTER_TRANSMIT_ONLY_CHANNEL = 0x50
TIMEOUT_NEVER = 0xFF
